---
deployment:
  tasks:
    - export DEPLOYPATH=/home/webk6347/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp contact.php $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH

