<?php
function e(string $value): string { return htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); }
function wa(string $message = 'Halo Webkubator, saya ingin konsultasi website.'): string { return 'https://wa.me/6287753719307?text=' . rawurlencode($message); }
$assetVersion = (string) max((int) @filemtime(__DIR__ . '/../styles.css'), (int) @filemtime(__DIR__ . '/../script.js'));
header('Cache-Control: no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
?>
<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#00032D">
    <meta name="description" content="Mengenal Webkubator, penyedia jasa pembuatan website profesional dan jasa website modern, cepat, responsif, serta terjangkau untuk bisnis di Indonesia."><meta name="robots" content="index,follow,max-image-preview:large">
    <meta property="og:type" content="website"><meta property="og:locale" content="id_ID"><meta property="og:title" content="Tentang Webkubator | Jasa Pembuatan Website Profesional"><meta property="og:description" content="Mengenal Webkubator, penyedia jasa pembuatan website profesional dan jasa website modern untuk bisnis di Indonesia."><meta property="og:url" content="https://webkubator.com/about/"><meta property="og:image" content="https://webkubator.com/assets/images/about.webp"><meta property="og:image:alt" content="Ilustrasi layanan jasa website Webkubator"><link rel="canonical" href="https://webkubator.com/about/"><link rel="icon" type="image/png" href="../assets/images/favicon.png?v=<?= e($assetVersion) ?>"><link rel="apple-touch-icon" href="../assets/images/favicon.png?v=<?= e($assetVersion) ?>">
    <title>Tentang Webkubator | Jasa Pembuatan Website Profesional</title>
    <script type="application/ld+json"><?= json_encode(['@context' => 'https://schema.org', '@type' => 'AboutPage', '@id' => 'https://webkubator.com/about/#webpage', 'url' => 'https://webkubator.com/about/', 'name' => 'Tentang Webkubator | Jasa Pembuatan Website Profesional', 'description' => 'Mengenal Webkubator, penyedia jasa pembuatan website profesional dan jasa website modern untuk bisnis di Indonesia.', 'inLanguage' => 'id-ID', 'isPartOf' => ['@id' => 'https://webkubator.com/#website'], 'about' => ['@type' => 'Organization', 'name' => 'Webkubator', 'url' => 'https://webkubator.com/']], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?></script>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link rel="preconnect" href="https://cdn-uicons.flaticon.com"><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&family=Roboto:wght@400;500;700&family=Ubuntu:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdn-uicons.flaticon.com/3.0.0/uicons-regular-rounded/css/uicons-regular-rounded.css">
    <link rel="stylesheet" href="../styles.css?v=<?= e($assetVersion) ?>">
</head>
<body>
    <a class="skip-link" href="#main-content">Lewati ke konten utama</a>
    <header class="site-header" data-header><div class="container header-inner"><div class="header-left"><a class="brand" href="../" aria-label="Webkubator, kembali ke halaman utama"><img src="../assets/images/logo-white.webp" alt="Logo Webkubator" width="48" height="48"><span>Webkubator</span></a></div><nav class="site-nav" id="site-nav" aria-label="Navigasi utama"><button class="menu-close" type="button" aria-label="Tutup menu navigasi">×</button><a href="../#service">Service</a><a href="../#pricing">Pricing</a><a href="./" aria-current="page">About</a><a href="../portofolio/">Portfolio</a><a href="../#contactus">Contact Us</a></nav><a class="header-contact button button-primary" href="<?= e(wa('Halo Webkubator, saya ingin memesan website.')) ?>" target="_blank" rel="noopener"><i class="fi fi-rr-paper-plane" aria-hidden="true"></i> Hubungi Kami</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="site-nav" aria-label="Buka menu navigasi"><span></span><span></span><span></span></button></div></header>
    <main id="main-content">
        <section class="section about-section about-page" id="about" aria-labelledby="about-title"><div class="container about-grid"><div class="about-visual reveal"><img src="../assets/images/about.webp" alt="Ilustrasi layanan jasa website Webkubator" width="768" height="512" fetchpriority="high"></div><div class="about-copy reveal reveal-delay-1"><p class="eyebrow">Tentang Webkubator</p><h1 id="about-title">Penyedia Jasa Pembuatan Website Profesional</h1><p><strong>Webkubator</strong> adalah penyedia jasa pembuatan website dan jasa website yang berfokus pada solusi digital cepat, efektif, dan terjangkau. Kami membantu UMKM serta perusahaan menghadirkan kehadiran online yang kuat dengan desain menarik, performa cepat, dan proses pengerjaan yang efisien.</p><p>Dengan komitmen untuk mendukung pertumbuhan bisnis melalui teknologi digital, kami tidak hanya membangun website, tetapi juga menciptakan pengalaman online yang memukau dan mudah digunakan oleh pelanggan.</p><a class="button button-primary" href="<?= e(wa('Halo Webkubator, saya ingin konsultasi website.')) ?>" target="_blank" rel="noopener"><i class="fi fi-rr-paper-plane" aria-hidden="true"></i> Hubungi Kami</a></div></div></section>
        <section class="section contact-section" id="contactus"><div class="container contact-shell reveal"><div><p class="eyebrow">Siap memulai?</p><h2>Bangun website <span>bisnis Anda</span></h2><p>Diskusikan kebutuhan website Anda bersama Webkubator.</p></div><div class="contact-list"><a class="contact-card" href="https://wa.me/6287753719307" target="_blank" rel="noopener"><span class="contact-icon">☎</span><span><small>Hubungi Kami</small><strong>(+62)87753719307</strong></span><b aria-hidden="true">↗</b></a><a class="contact-card" href="mailto:webkubator@gmail.com"><span class="contact-icon">@</span><span><small>Email</small><strong>webkubator@gmail.com</strong></span><b aria-hidden="true">↗</b></a></div></div></section>
    </main>
    <footer class="site-footer"><div class="container footer-inner"><a class="brand" href="../" aria-label="Kembali ke halaman utama"><img src="../assets/images/logo-white.webp" alt="Webkubator" width="52" height="52"></a><p>Solusi website cepat untuk bisnis modern.</p><div class="footer-bottom"><span>Copyright © 2025 Webkubator | Powered by Webkubator</span><a href="./">Kembali ke atas ↑</a></div></div></footer>
    <a class="whatsapp-float" href="https://wa.me/6287753719307" target="_blank" rel="noopener" aria-label="Hubungi Webkubator melalui WhatsApp"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.08 0C5.55 0 .24 5.3.24 11.83c0 2.08.54 4.11 1.57 5.9L.14 23.85l6.27-1.64a11.8 11.8 0 0 0 5.66 1.44h.01c6.52 0 11.83-5.3 11.83-11.82 0-3.16-1.23-6.13-3.41-8.33ZM12.08 21.6h-.01a9.77 9.77 0 0 1-4.98-1.36l-.36-.22-3.72.98 1-3.62-.24-.37a9.77 9.77 0 0 1-1.5-5.18c0-5.38 4.38-9.76 9.77-9.76a9.7 9.7 0 0 1 6.91 2.87 9.7 9.7 0 0 1 2.86 6.92c0 5.38-4.38 9.75-9.75 9.75Zm5.35-7.3c-.29-.15-1.72-.85-1.99-.94-.27-.1-.46-.15-.65.15-.2.29-.75.94-.92 1.13-.17.2-.34.22-.63.08-.29-.15-1.24-.46-2.36-1.46a8.9 8.9 0 0 1-1.64-2.03c-.17-.29-.02-.45.13-.6.13-.13.29-.34.44-.51.15-.17.2-.29.3-.49.1-.2.05-.37-.02-.52-.08-.15-.65-1.57-.89-2.15-.23-.56-.47-.49-.65-.5h-.55c-.2 0-.52.07-.8.37-.27.29-1.04 1.02-1.04 2.49 0 1.47 1.07 2.89 1.21 3.09.15.2 2.1 3.2 5.1 4.49.71.31 1.27.5 1.7.64.71.23 1.36.2 1.87.12.57-.08 1.72-.7 1.96-1.38.24-.68.24-1.26.17-1.38-.07-.12-.27-.2-.56-.34Z"/></svg></a>
    <script src="../script.js?v=<?= e($assetVersion) ?>" defer></script>
</body>
</html>
